// Make medicines array globally available with comprehensive details
window.medicines = [
    // Pain & Fever (1-10)
    {
        name: 'Acetaminophen (Paracetamol)',
        uses: 'Mild to moderate pain, fever reduction',
        dosage: '325-1000mg every 4-6 hours (max 4000mg/day)',
        mechanism: 'Inhibits prostaglandin synthesis in the central nervous system',
        onset: '30 minutes to 1 hour',
        duration: '4-6 hours',
        sideEffects: [
            'Nausea',
            'Stomach pain',
            'Loss of appetite',
            'Itching',
            'Rash',
            'Dark urine',
            'Yellowing of skin/eyes',
            'Severe fatigue',
            'Unusual bleeding/bruising'
        ],
        precautions: [
            'Do not exceed recommended dosage',
            'Avoid alcohol consumption',
            'Consult doctor if pregnant or breastfeeding',
            'Caution with liver disease',
            'Check other medications for acetaminophen content'
        ],
        howToTake: 'Take with or without food. Swallow tablet whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'B',
        pregnancyNotes: 'Generally considered safe during pregnancy when used as directed',
        breastfeedingInfo: 'Small amounts pass into breast milk but generally considered safe',
        category: 'Analgesic/Antipyretic',
        manufacturer: 'Various manufacturers',
        otherNames: ['Tylenol', 'Panadol', 'Calpol', 'Dolo']
    },
    {
        name: 'Ibuprofen',
        uses: 'Pain, inflammation, fever',
        dosage: '200-400mg every 4-6 hours (max 1200mg/day)',
        mechanism: 'Inhibits cyclooxygenase (COX) enzymes, reducing prostaglandin production',
        onset: '20-30 minutes',
        duration: '4-6 hours',
        sideEffects: [
            'Stomach pain',
            'Heartburn',
            'Dizziness',
            'Mild headache',
            'Constipation or diarrhea',
            'Mild itching or rash',
            'Ringing in the ears'
        ],
        precautions: [
            'Take with food or milk',
            'Avoid in third trimester of pregnancy',
            'Not recommended for people with stomach ulcers',
            'Caution in heart disease, high blood pressure',
            'May increase risk of heart attack or stroke'
        ],
        howToTake: 'Take with food or milk to prevent stomach upset',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store at room temperature away from moisture and heat',
        pregnancyCategory: 'C (first and second trimester), D (third trimester)',
        pregnancyNotes: 'Avoid in third trimester',
        breastfeedingInfo: 'Small amounts pass into breast milk but generally considered safe',
        category: 'NSAID',
        manufacturer: 'Various manufacturers',
        otherNames: ['Advil', 'Motrin', 'Nurofen', 'Brufen']
    },
    {
        name: 'Naproxen',
        uses: 'Arthritis, menstrual cramps, pain, inflammation',
        dosage: '220-550mg every 12 hours',
        mechanism: 'Nonsteroidal anti-inflammatory drug (NSAID) that reduces hormones causing inflammation and pain',
        onset: '1 hour',
        duration: '8-12 hours',
        sideEffects: [
            'Stomach pain',
            'Heartburn',
            'Drowsiness',
            'Headache',
            'Dizziness',
            'Mild headache',
            'Mild itching or rash',
            'Ringing in the ears',
            'Vision changes'
        ],
        precautions: [
            'Take with food or milk',
            'Avoid in third trimester of pregnancy',
            'Not recommended for people with stomach ulcers',
            'May increase risk of heart attack or stroke',
            'Caution in heart disease, high blood pressure',
            'May cause drowsiness or dizziness'
        ],
        howToTake: 'Take with food or milk to prevent stomach upset. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store at room temperature away from moisture and heat',
        pregnancyCategory: 'C (first and second trimester), D (third trimester)',
        pregnancyNotes: 'Avoid in third trimester',
        breastfeedingInfo: 'Small amounts pass into breast milk, consult doctor',
        category: 'NSAID',
        manufacturer: 'Various manufacturers',
        otherNames: ['Aleve', 'Naprosyn', 'Anaprox', 'Naprelan']
    },
    {
        name: 'Aspirin (Acetylsalicylic Acid)',
        uses: 'Pain, fever, inflammation, prevention of heart attacks and strokes',
        dosage: '325-650mg every 4-6 hours (pain/fever), 75-325mg daily (heart protection)',
        mechanism: 'Irreversibly inhibits cyclooxygenase enzymes, reducing prostaglandin and thromboxane synthesis',
        onset: '5-30 minutes (pain relief)',
        duration: '3-6 hours (analgesic effect)',
        sideEffects: [
            'Stomach pain',
            'Heartburn',
            'Nausea',
            'Vomiting',
            'Increased bleeding tendency',
            'Ringing in ears (tinnitus)',
            'Dizziness',
            'Allergic reactions',
            'Stomach ulcers',
            'Gastrointestinal bleeding'
        ],
        precautions: [
            'Avoid in children and teenagers with viral infections (risk of Reye\'s syndrome)',
            'Take with food or milk to reduce stomach upset',
            'Inform dentist/surgeon before procedures (bleeding risk)',
            'Avoid alcohol (increases bleeding risk)',
            'Not for use in third trimester of pregnancy',
            'Caution in asthma, ulcers, bleeding disorders'
        ],
        howToTake: 'Take with food or full glass of water. Do not lie down for 10 minutes after taking.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store at room temperature away from moisture and heat',
        pregnancyCategory: 'D (third trimester)',
        pregnancyNotes: 'Avoid in third trimester',
        breastfeedingInfo: 'Small amounts pass into breast milk, consult doctor',
        category: 'NSAID, Antiplatelet',
        manufacturer: 'Various manufacturers',
        otherNames: ['Bayer', 'Ecotrin', 'Disprin', 'Aspro']
    },
    {
        name: 'Diclofenac',
        uses: 'Osteoarthritis, rheumatoid arthritis, ankylosing spondylitis, acute pain',
        dosage: '50mg 2-3 times daily (immediate release), 100mg once daily (extended release)',
        mechanism: 'Nonsteroidal anti-inflammatory drug (NSAID) that inhibits cyclooxygenase (COX) enzymes, reducing prostaglandin production',
        onset: '30 minutes to 1 hour',
        duration: '8-12 hours (extended release)',
        sideEffects: [
            'Stomach pain/heartburn',
            'Nausea/vomiting',
            'Diarrhea/constipation',
            'Gas/bloating',
            'Dizziness',
            'Headache',
            'Mild itching or rash',
            'Ringing in ears',
            'Fluid retention/swelling',
            'Increased blood pressure'
        ],
        precautions: [
            'Take with food or milk',
            'Avoid alcohol (increases stomach bleeding risk)',
            'Not recommended for CABG surgery pain',
            'May increase risk of heart attack/stroke',
            'Caution in heart disease, high blood pressure',
            'Avoid in late pregnancy',
            'May make skin more sensitive to sunlight'
        ],
        howToTake: 'Swallow whole with water, do not crush or chew. Take with food or milk.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store at room temperature away from moisture and heat',
        pregnancyCategory: 'D (third trimester)',
        pregnancyNotes: 'Avoid in third trimester',
        breastfeedingInfo: 'Not recommended during breastfeeding',
        category: 'NSAID',
        manufacturer: 'Various manufacturers',
        otherNames: ['Voltaren', 'Cataflam', 'Zipsor', 'Zorvolex']
    },
    {
        name: 'Celecoxib',
        uses: 'Osteoarthritis, rheumatoid arthritis, ankylosing spondylitis, acute pain',
        dosage: '100-200mg once or twice daily (max 400mg/day)',
        mechanism: 'Selective COX-2 inhibitor that reduces prostaglandin production with less effect on stomach lining',
        onset: 'Within 1 hour',
        duration: '12 hours',
        sideEffects: [
            'Headache',
            'Stomach pain',
            'Diarrhea',
            'Indigestion',
            'Nausea',
            'Swelling of hands/ankles/feet',
            'Dizziness',
            'Trouble sleeping',
            'Mild rash/itching'
        ],
        precautions: [
            'Take with food if stomach upset occurs',
            'May increase risk of heart attack/stroke',
            'Not for use before/after heart bypass surgery',
            'Caution in heart disease, high blood pressure',
            'May cause new or worsening high blood pressure',
            'Avoid in late pregnancy',
            'May make skin more sensitive to sunlight'
        ],
        howToTake: 'Take with a full glass of water. May take with food if stomach upset occurs.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store at room temperature away from moisture and heat',
        pregnancyCategory: 'D (third trimester)',
        pregnancyNotes: 'Avoid in third trimester',
        breastfeedingInfo: 'Not recommended during breastfeeding',
        category: 'NSAID, COX-2 Inhibitor',
        manufacturer: 'Pfizer',
        otherNames: ['Celebrex']
    },
    {
        name: 'Tramadol',
        uses: 'Moderate to moderately severe pain',
        dosage: '50-100mg every 4-6 hours (max 400mg/day)',
        mechanism: 'Opioid agonist that binds to mu-opioid receptors and inhibits norepinephrine and serotonin reuptake',
        onset: 'Within 1 hour',
        duration: '4-6 hours',
        sideEffects: [
            'Dizziness/vertigo',
            'Nausea/vomiting',
            'Constipation',
            'Headache',
            'Drowsiness',
            'Dry mouth',
            'Sweating',
            'Fatigue',
            'Itching',
            'Seizures (at high doses)'
        ],
        precautions: [
            'High risk of addiction and dependence',
            'Avoid alcohol (increases risk of side effects)',
            'Not for narcotic-dependent patients',
            'May impair thinking/reactions',
            'Do not stop suddenly (withdrawal symptoms)',
            'Caution in elderly, liver/kidney disease',
            'Avoid with MAO inhibitors',
            'May cause serotonin syndrome'
        ],
        howToTake: 'Take with or without food. Swallow extended-release tablets whole.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store at room temperature away from moisture and heat',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Not recommended during pregnancy (risk of neonatal withdrawal)',
        breastfeedingInfo: 'Not recommended (passes into breast milk)',
        category: 'Opioid Analgesic',
        manufacturer: 'Various manufacturers',
        otherNames: ['Ultram', 'ConZip', 'Rybix', 'Ralivia']
    },
    {
        name: 'Codeine',
        uses: 'Mild to moderate pain, cough suppression, diarrhea',
        dosage: '15-60mg every 4-6 hours (pain), 10-20mg every 4-6 hours (cough)',
        mechanism: 'Opioid agonist that binds to mu-opioid receptors in the CNS, also suppresses cough reflex',
        onset: '30-60 minutes',
        duration: '4-6 hours',
        sideEffects: [
            'Drowsiness/dizziness',
            'Nausea/vomiting',
            'Constipation',
            'Stomach pain',
            'Sweating',
            'Mood changes',
            'Dry mouth',
            'Headache',
            'Fatigue',
            'Difficulty urinating'
        ],
        precautions: [
            'High risk of addiction and dependence',
            'Avoid alcohol (dangerous respiratory depression)',
            'Not for children under 12 (respiratory depression risk)',
            'Caution in asthma/breathing problems',
            'May cause life-threatening breathing problems in some people',
            'Avoid with MAO inhibitors',
            'Caution in elderly, liver/kidney disease'
        ],
        howToTake: 'Take with food or milk if stomach upset occurs. Swallow whole.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C (D if used for prolonged periods)',
        pregnancyNotes: 'Avoid during labor (respiratory depression in newborn)',
        breastfeedingInfo: 'Not recommended (passes into breast milk)',
        category: 'Opioid Analgesic, Antitussive',
        manufacturer: 'Various manufacturers',
        otherNames: ['Codeine Phosphate', 'Codeine Sulfate']
    },
    {
        name: 'Acetaminophen/Hydrocodone',
        uses: 'Moderate to moderately severe pain',
        dosage: '2.5-10mg hydrocodone with 300-325mg acetaminophen every 4-6 hours (max 4000mg acetaminophen/24hr)',
        mechanism: 'Hydrocodone: Binds to opioid receptors in CNS; Acetaminophen: Inhibits prostaglandin synthesis',
        onset: '10-30 minutes',
        duration: '4-6 hours',
        sideEffects: [
            'Drowsiness/dizziness',
            'Nausea/vomiting',
            'Constipation',
            'Stomach pain',
            'Headache',
            'Dry mouth',
            'Sweating',
            'Mood changes',
            'Itching',
            'Difficulty urinating'
        ],
        precautions: [
            'High risk of addiction and dependence',
            'Do not exceed 4000mg acetaminophen/day',
            'Avoid alcohol (increases liver toxicity risk)',
            'May impair thinking/reactions',
            'Not for narcotic-dependent patients',
            'Caution in elderly, liver/kidney disease',
            'Avoid with MAO inhibitors',
            'Monitor for signs of liver damage'
        ],
        howToTake: 'Take with or without food. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C (D if used for prolonged periods)',
        pregnancyNotes: 'Avoid during labor (respiratory depression in newborn)',
        breastfeedingInfo: 'Not recommended (passes into breast milk)',
        category: 'Opioid Analgesic Combination',
        manufacturer: 'Various manufacturers',
        otherNames: ['Vicodin', 'Norco', 'Lortab', 'Lorcet']
    },
    {
        name: 'Meloxicam',
        uses: 'Osteoarthritis, rheumatoid arthritis, juvenile rheumatoid arthritis',
        dosage: '7.5-15mg once daily (max 15mg/day)',
        mechanism: 'Selective COX-2 inhibitor NSAID that reduces hormones causing inflammation and pain',
        onset: '2-3 hours',
        duration: '24 hours',
        sideEffects: [
            'Stomach pain/heartburn',
            'Nausea/vomiting',
            'Diarrhea/constipation',
            'Gas/bloating',
            'Dizziness',
            'Headache',
            'Mild itching or rash',
            'Swelling of hands/feet',
            'Increased blood pressure',
            'Fluid retention'
        ],
        precautions: [
            'Take with food or milk',
            'Avoid alcohol (increases stomach bleeding risk)',
            'May increase risk of heart attack/stroke',
            'Not for use before/after heart bypass surgery',
            'Caution in heart disease, high blood pressure',
            'Avoid in late pregnancy',
            'May make skin more sensitive to sunlight'
        ],
        howToTake: 'Take with food or milk to prevent stomach upset. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store at room temperature away from moisture and heat',
        pregnancyCategory: 'D (third trimester)',
        pregnancyNotes: 'Avoid in third trimester',
        breastfeedingInfo: 'Not recommended during breastfeeding',
        category: 'NSAID, COX-2 Inhibitor',
        manufacturer: 'Various manufacturers',
        otherNames: ['Mobic', 'Vivlodex', 'Qmiiz ODT']
    },
    // Antibiotics (11-30)
    {
        name: 'Amoxicillin',
        uses: 'Bacterial infections (ear, nose, throat, skin, urinary tract, pneumonia, bronchitis)',
        dosage: '250-500mg every 8 hours (adults), 20-90mg/kg/day divided every 8-12 hours (children)',
        mechanism: 'Beta-lactam antibiotic that inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins',
        onset: 'Rapid absorption, peak levels in 1-2 hours',
        duration: '6-8 hours (typical dosing interval)',
        sideEffects: [
            'Diarrhea',
            'Nausea/vomiting',
            'Stomach pain',
            'Headache',
            'Skin rash',
            'Vaginal yeast infection',
            'Mild allergic reactions (hives, itching)',
            'Black/tarry stools',
            'Yellowing of eyes/skin'
        ],
        precautions: [
            'Complete full course as prescribed',
            'May reduce effectiveness of birth control pills',
            'Take at start of meal to enhance absorption',
            'Report severe diarrhea, abdominal pain, or bloody stools',
            'Inform doctor of any history of kidney disease',
            'May cause false positive urine glucose tests',
            'Use additional contraception if on birth control pills'
        ],
        howToTake: 'Take with or without food. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store at room temperature away from moisture and heat. Refrigerate liquid form.',
        pregnancyCategory: 'B',
        pregnancyNotes: 'Generally considered safe during pregnancy',
        breastfeedingInfo: 'Small amounts pass into breast milk but generally considered safe',
        category: 'Antibiotic/Penicillin',
        manufacturer: 'Various manufacturers',
        otherNames: ['Amoxil', 'Moxatag', 'Trimox']
    },
    {
        name: 'Amoxicillin/Clavulanate',
        uses: 'Bacterial infections (sinusitis, pneumonia, otitis media, skin infections, urinary tract infections)',
        dosage: '250-500mg amoxicillin/125mg clavulanate every 8 hours or 875/125mg every 12 hours',
        mechanism: 'Amoxicillin: Inhibits bacterial cell wall synthesis; Clavulanate: Beta-lactamase inhibitor that protects amoxicillin from degradation',
        onset: 'Rapid absorption, peak levels in 1-2 hours',
        duration: '6-8 hours (typical dosing interval)',
        sideEffects: [
            'Diarrhea (more common than with amoxicillin alone)',
            'Nausea/vomiting',
            'Stomach pain',
            'Headache',
            'Skin rash',
            'Vaginal yeast infection',
            'Mild allergic reactions',
            'Liver enzyme elevation',
            'Gas/bloating'
        ],
        precautions: [
            'Take at start of a meal to enhance absorption and reduce stomach upset',
            'Complete full course as prescribed',
            'May reduce effectiveness of birth control pills',
            'Higher incidence of diarrhea than amoxicillin alone',
            'Monitor for signs of liver problems (dark urine, yellowing skin/eyes)',
            'Inform doctor of any history of liver disease',
            'May cause false positive urine glucose tests'
        ],
        howToTake: 'Take at the start of a meal. Swallow whole with water. Do not crush or chew extended-release tablets.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store at room temperature away from moisture and heat. Refrigerate liquid form.',
        pregnancyCategory: 'B',
        pregnancyNotes: 'Generally considered safe during pregnancy when clearly needed',
        breastfeedingInfo: 'Small amounts pass into breast milk but generally considered safe',
        category: 'Antibiotic/Beta-lactamase inhibitor',
        manufacturer: 'GlaxoSmithKline',
        otherNames: ['Augmentin', 'Amoclan', 'Augmentin XR']
    },
    {
        name: 'Azithromycin',
        uses: 'Respiratory infections (pneumonia, bronchitis, sinusitis), skin infections, STIs (chlamydia), ear infections, some STDs',
        dosage: '500mg day 1, then 250mg daily for 4 more days (typical 5-day course); 1g single dose for chlamydia',
        mechanism: 'Macrolide antibiotic that inhibits bacterial protein synthesis by binding to the 50S ribosomal subunit',
        onset: '2-4 hours',
        duration: 'Long tissue half-life allows once-daily dosing',
        sideEffects: [
            'Diarrhea/loose stools',
            'Nausea/vomiting',
            'Stomach pain',
            'Headache',
            'Dizziness',
            'Mild skin rash',
            'Changes in taste',
            'Vaginal yeast infection',
            'QT prolongation (rare)'
        ],
        precautions: [
            'Take 1 hour before or 2 hours after food for best absorption',
            'May cause diarrhea (contact doctor if severe or bloody)',
            'May worsen myasthenia gravis',
            'Caution in liver disease',
            'May increase effects of blood thinners',
            'Report fast/irregular heartbeat, severe dizziness',
            'Complete full course as prescribed'
        ],
        howToTake: 'Take on an empty stomach (1 hour before or 2 hours after food) with a full glass of water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store at room temperature away from moisture and heat',
        pregnancyCategory: 'B',
        pregnancyNotes: 'Generally considered safe during pregnancy when clearly needed',
        breastfeedingInfo: 'Small amounts pass into breast milk but generally considered safe',
        category: 'Antibiotic/Macrolide',
        manufacturer: 'Pfizer',
        otherNames: ['Zithromax', 'Z-Pak', 'AzaSite (eye drops)']
    },
    {
        name: 'Cephalexin',
        uses: 'Skin/skin structure infections, bone infections, respiratory tract infections, otitis media, urinary tract infections',
        dosage: '250-500mg every 6 hours (adults), 25-100mg/kg/day divided every 6-12 hours (children)',
        mechanism: 'First-generation cephalosporin antibiotic that inhibits bacterial cell wall synthesis',
        onset: 'Rapid absorption, peak levels in 1 hour',
        duration: '6-8 hours (typical dosing interval)',
        sideEffects: [
            'Diarrhea',
            'Nausea/vomiting',
            'Stomach pain',
            'Heartburn',
            'Dizziness',
            'Fatigue',
            'Headache',
            'Joint pain',
            'Vaginal itching/discharge',
            'Mild skin rash'
        ],
        precautions: [
            'Take with food if stomach upset occurs',
            'Complete full course as prescribed',
            'May cause diarrhea (contact doctor if severe or bloody)',
            'Use with caution in penicillin allergy (cross-reactivity possible)',
            'May cause false positive urine glucose tests',
            'May increase effects of blood thinners',
            'Store suspension in refrigerator'
        ],
        howToTake: 'Take with food or milk to prevent stomach upset. Shake liquid form well before measuring dose.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose.',
        storage: 'Store capsules/tablets at room temperature. Refrigerate liquid form and discard after 14 days.',
        pregnancyCategory: 'B',
        pregnancyNotes: 'Generally considered safe during pregnancy when clearly needed',
        breastfeedingInfo: 'Small amounts pass into breast milk but generally considered safe',
        category: 'Antibiotic/Cephalosporin (1st generation)',
        manufacturer: 'Various manufacturers',
        otherNames: ['Keflex', 'Daxbia', 'Zartan']
    },
    {
        name: 'Ciprofloxacin',
        uses: 'Urinary tract infections, respiratory infections, skin infections, bone/joint infections, infectious diarrhea, typhoid fever, anthrax exposure',
        dosage: '250-750mg every 12 hours (oral), duration varies by infection type',
        mechanism: 'Fluoroquinolone antibiotic that inhibits bacterial DNA gyrase and topoisomerase IV, preventing DNA replication',
        onset: '1-2 hours (oral)',
        duration: '12-hour dosing interval for most infections',
        sideEffects: [
            'Nausea/vomiting',
            'Diarrhea',
            'Headache',
            'Dizziness',
            'Insomnia',
            'Photosensitivity',
            'Tendon rupture (rare but serious)',
            'Peripheral neuropathy',
            'QT prolongation',
            'Hypoglycemia (in diabetics)'
        ],
        precautions: [
            'Take 2 hours before or 6 hours after dairy/antacids/iron/zinc supplements',
            'Drink plenty of fluids',
            'Avoid excessive sunlight/tanning beds (increased photosensitivity)',
            'Report tendon pain/weakness immediately',
            'May cause dizziness (use caution when driving)',
            'Not recommended for children under 18 (except for specific conditions)',
            'May increase blood sugar (monitor if diabetic)'
        ],
        howToTake: 'Take with a full glass of water, 2 hours before or 6 hours after dairy/antacids. Complete full course as prescribed.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Use only if potential benefit justifies potential risk to fetus',
        breastfeedingInfo: 'Not recommended (passes into breast milk)',
        category: 'Antibiotic/Fluoroquinolone',
        manufacturer: 'Bayer',
        otherNames: ['Cipro', 'Ciprobay', 'Cetraxal']
    },
    {
        name: 'Doxycycline',
        uses: 'Acne, rosacea, respiratory infections, Lyme disease, chlamydia, malaria prevention, anthrax exposure',
        dosage: '50-100mg every 12-24 hours (varies by condition)',
        mechanism: 'Tetracycline antibiotic that inhibits bacterial protein synthesis by binding to the 30S ribosomal subunit',
        onset: '1-2 hours (oral)',
        duration: '12-24 hour dosing interval',
        sideEffects: [
            'Nausea/vomiting',
            'Diarrhea',
            'Stomach upset',
            'Loss of appetite',
            'Photosensitivity',
            'Tooth discoloration (in children)',
            'Esophageal irritation',
            'Vaginal yeast infection',
            'Mild skin rash'
        ],
        precautions: [
            'Take with food or milk if stomach upset occurs',
            'Take with a full glass of water and remain upright for 30 minutes',
            'Use sunscreen and protective clothing (increased sun sensitivity)',
            'Avoid dairy/calcium/iron/magnesium supplements within 2-3 hours',
            'Not for children under 8 years (tooth discoloration risk)',
            'May make birth control pills less effective',
            'Report severe headache, vision changes, or skin reactions'
        ],
        howToTake: 'Take with a full glass of water while sitting or standing. Avoid lying down for at least 30 minutes after taking.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'D',
        pregnancyNotes: 'Contraindicated in pregnancy (may cause permanent tooth discoloration in fetus)',
        breastfeedingInfo: 'Not recommended (may affect bone/tooth development in nursing infant)',
        category: 'Antibiotic/Tetracycline',
        manufacturer: 'Various manufacturers',
        otherNames: ['Vibramycin', 'Doryx', 'Oracea', 'Monodox']
    },
    {
        name: 'Levofloxacin',
        uses: 'Pneumonia, sinusitis, urinary tract infections, skin infections, chronic bronchitis, anthrax exposure',
        dosage: '250-750mg once daily (varies by infection type and severity)',
        mechanism: 'Fluoroquinolone antibiotic that inhibits bacterial DNA gyrase and topoisomerase IV, preventing DNA replication',
        onset: '1-2 hours (oral)',
        duration: '24-hour dosing interval for most infections',
        sideEffects: [
            'Nausea/vomiting',
            'Diarrhea',
            'Headache',
            'Dizziness',
            'Insomnia',
            'Photosensitivity',
            'Tendon rupture (rare but serious)',
            'Peripheral neuropathy',
            'QT prolongation',
            'Hypoglycemia (in diabetics)'
        ],
        precautions: [
            'Take 2 hours before or 2 hours after dairy/antacids/iron/zinc supplements',
            'Drink plenty of fluids to prevent crystalluria',
            'Avoid excessive sunlight/tanning beds',
            'Report tendon pain/weakness immediately',
            'May cause dizziness (use caution when driving)',
            'Not recommended for children under 18 (except for specific conditions)',
            'May increase blood sugar (monitor if diabetic)'
        ],
        howToTake: 'Take with a full glass of water, with or without food. Complete full course as prescribed.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Use only if potential benefit justifies potential risk to fetus',
        breastfeedingInfo: 'Not recommended (passes into breast milk)',
        category: 'Antibiotic/Fluoroquinolone',
        manufacturer: 'Daiichi Sankyo',
        otherNames: ['Levaquin', 'Iquix (eye drops)', 'Quixin (eye drops)']
    },
    {
        name: 'Metronidazole',
        uses: 'Bacterial infections (anaerobes), parasitic infections (trichomoniasis, giardiasis, amebiasis), H. pylori eradication, bacterial vaginosis',
        dosage: '250-750mg three times daily (varies by condition), 500mg twice daily for bacterial vaginosis',
        mechanism: 'Nitroimidazole antibiotic that disrupts DNA and protein synthesis in susceptible organisms',
        onset: '1-2 hours (oral)',
        duration: '8-12 hour dosing interval',
        sideEffects: [
            'Metallic taste',
            'Nausea/vomiting',
            'Loss of appetite',
            'Abdominal cramps',
            'Headache',
            'Dry mouth',
            'Dark-colored urine',
            'Dizziness',
            'Yeast infection',
            'Peripheral neuropathy (with long-term use)'
        ],
        precautions: [
            'STRICT avoidance of alcohol during and for 3 days after treatment',
            'Take with food to minimize stomach upset',
            'May cause dizziness (use caution when driving)',
            'May cause urine to darken (harmless effect)',
            'Complete full course as prescribed',
            'Use additional contraception if on birth control pills',
            'Caution in patients with CNS disorders'
        ],
        howToTake: 'Take with food or milk to prevent stomach upset. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'B',
        pregnancyNotes: 'Avoid in first trimester unless clearly needed',
        breastfeedingInfo: 'Not recommended during treatment and for 24-48 hours after last dose',
    },
    {
        name: 'Lisinopril',
        uses: 'Hypertension (high blood pressure), heart failure, post-heart attack treatment, diabetic kidney disease',
        dosage: '10-40mg once daily (hypertension), 5-40mg daily (heart failure)',
        mechanism: 'Angiotensin-converting enzyme (ACE) inhibitor that prevents the formation of angiotensin II, causing blood vessels to relax',
        onset: '1 hour (peak effect in 6 hours)',
        duration: '24 hours',
        sideEffects: [
            'Dry cough (common)',
            'Dizziness/lightheadedness',
            'Headache',
            'Fatigue',
            'Hyperkalemia (high potassium)',
            'Hypotension (low blood pressure)',
            'Impaired kidney function',
            'Rash',
            'Angioedema (rare but serious)'
        ],
        precautions: [
            'Monitor kidney function and potassium levels',
            'Risk of angioedema (swelling of face/lips/tongue/throat)',
            'May cause dizziness (rise slowly from sitting/lying position)',
            'Avoid potassium supplements/salt substitutes unless directed by doctor',
            'Stay hydrated to prevent low blood pressure',
            'Avoid alcohol (may increase blood pressure-lowering effect)',
            'Not for use during pregnancy (can cause fetal harm)'
        ],
        howToTake: 'Take with or without food, at the same time each day. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'D',
        pregnancyNotes: 'Contraindicated in pregnancy (risk of fetal harm or death)',
        breastfeedingInfo: 'Not recommended (passes into breast milk)',
        category: 'Antihypertensive/ACE Inhibitor',
        manufacturer: 'Various manufacturers',
        otherNames: ['Zestril', 'Prinivil', 'Qbrelis']
    },
    {
        name: 'Amlodipine',
        uses: 'Hypertension (high blood pressure), chronic stable angina, vasospastic angina',
        dosage: '2.5-10mg once daily (usual maintenance: 5-10mg daily)',
        mechanism: 'Dihydropyridine calcium channel blocker that relaxes blood vessels by blocking calcium influx into vascular smooth muscle',
        onset: '6-12 hours (peak effect in 24-48 hours)',
        duration: '24 hours',
        sideEffects: [
            'Peripheral edema (swelling of hands/ankles/feet)',
            'Dizziness/lightheadedness',
            'Flushing',
            'Palpitations',
            'Headache',
            'Fatigue',
            'Nausea',
            'Abdominal pain',
            'Drowsiness'
        ],
        precautions: [
            'Avoid grapefruit/grapefruit juice (increases drug levels)',
            'Rise slowly from sitting/lying position',
            'May cause dizziness (use caution when driving)',
            'Monitor for signs of worsening chest pain or heart attack',
            'Dose adjustments may be needed in liver disease',
            'Avoid excessive alcohol consumption',
            'Report irregular heartbeat, severe dizziness, or swelling of hands/feet'
        ],
        howToTake: 'Take with or without food, at the same time each day. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Use only if potential benefit justifies potential risk to fetus',
        breastfeedingInfo: 'Not recommended (passes into breast milk)',
        category: 'Antihypertensive/Calcium Channel Blocker',
        manufacturer: 'Pfizer',
        otherNames: ['Norvasc', 'Katerzia', 'Amlopin']
    },
    {
        name: 'Metoprolol',
        uses: 'Hypertension (high blood pressure), angina, heart failure, heart attack recovery, abnormal heart rhythms',
        dosage: '25-200mg daily in 1-2 divided doses (tartrate), 25-400mg once daily (succinate ER)',
        mechanism: 'Selective beta-1 adrenergic receptor blocker that reduces heart rate, blood pressure, and myocardial oxygen demand',
        onset: '15 minutes (IV), 1-2 hours (oral)',
        duration: '3-6 hours (tartrate), 24 hours (succinate ER)',
        sideEffects: [
            'Fatigue',
            'Dizziness/lightheadedness',
            'Slow heart rate (bradycardia)',
            'Cold hands/feet',
            'Depression',
            'Shortness of breath',
            'Sleep problems',
            'Nausea',
            'Dry mouth',
            'Reduced exercise tolerance'
        ],
        precautions: [
            'DO NOT stop suddenly (taper over 1-2 weeks)',
            'Monitor heart rate and blood pressure',
            'May mask symptoms of low blood sugar in diabetics',
            'Caution in asthma/COPD (can cause bronchospasm)',
            'May worsen heart failure symptoms initially',
            'Avoid alcohol (may increase blood pressure-lowering effect)',
            'Report shortness of breath, swelling, or slow/irregular heartbeat'
        ],
        howToTake: 'Take with or immediately after meals. Swallow extended-release tablets whole; do not crush or chew.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C (D in second/third trimester)',
        pregnancyNotes: 'Use only if potential benefit justifies potential risk to fetus',
        breastfeedingInfo: 'Small amounts pass into breast milk; use with caution',
        category: 'Antihypertensive/Beta Blocker',
        manufacturer: 'Various manufacturers',
        otherNames: ['Lopressor', 'Toprol XL', 'Metolar']
    },
    {
        name: 'Losartan',
        uses: 'Hypertension (high blood pressure), diabetic nephropathy in type 2 diabetes, stroke risk reduction in hypertension with left ventricular hypertrophy',
        dosage: '25-100mg once daily (hypertension), 50-100mg daily (diabetic nephropathy)',
        mechanism: 'Angiotensin II receptor blocker (ARB) that blocks the vasoconstrictor effects of angiotensin II, causing blood vessels to relax',
        onset: '6 hours',
        duration: '24 hours',
        sideEffects: [
            'Dizziness',
            'Stuffy nose',
            'Back pain',
            'Low blood pressure',
            'Fatigue',
            'Hypoglycemia (in diabetics)',
            'Hyperkalemia (high potassium)',
            'Muscle cramps',
            'Stomach pain',
            'Chest pain'
        ],
        precautions: [
            'Monitor kidney function and potassium levels',
            'Stay well-hydrated (especially in hot weather or during exercise)',
            'May cause dizziness (rise slowly from sitting/lying position)',
            'Avoid potassium supplements/salt substitutes unless directed by doctor',
            'Not for use during pregnancy (risk of fetal harm)',
            'Caution in kidney/liver disease',
            'Report symptoms of high potassium (muscle weakness, irregular heartbeat)'
        ],
        howToTake: 'Take with or without food, at the same time each day. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'D (second and third trimesters)',
        pregnancyNotes: 'Contraindicated in pregnancy (risk of fetal harm or death)',
        breastfeedingInfo: 'Not recommended (passes into breast milk)',
        category: 'Antihypertensive/ARB',
        manufacturer: 'Merck & Co.',
        otherNames: ['Cozaar', 'Losacard', 'Repace']
    },
    {
        name: 'Atorvastatin',
        uses: 'High cholesterol, high triglycerides, prevention of cardiovascular disease (heart attack, stroke) in high-risk patients',
        dosage: '10-80mg once daily (individualized based on LDL goals)',
        mechanism: 'HMG-CoA reductase inhibitor (statin) that blocks cholesterol production in the liver and increases LDL receptor expression',
        onset: '1-2 weeks (lipid-lowering effects)',
        duration: '24 hours',
        sideEffects: [
            'Muscle pain/tenderness/weakness (myalgia)',
            'Digestive issues (nausea, diarrhea, constipation)',
            'Headache',
            'Liver enzyme abnormalities',
            'Increased blood sugar/diabetes risk',
            'Memory loss/confusion (rare)',
            'Liver damage (rare)',
            'Rhabdomyolysis (very rare)'
        ],
        precautions: [
            'Take at any time of day (with or without food)',
            'Avoid grapefruit/grapefruit juice (increases drug levels)',
            'Report unexplained muscle pain/tenderness/weakness immediately',
            'Limit alcohol consumption',
            'May increase blood sugar (monitor if diabetic)',
            'Avoid in active liver disease or unexplained persistent liver enzyme elevations',
            'Use with caution in elderly patients'
        ],
        howToTake: 'Take at any time of day, with or without food. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'X',
        pregnancyNotes: 'Contraindicated in pregnancy (risk of fetal harm)',
        breastfeedingInfo: 'Contraindicated (may cause serious side effects in nursing infant)',
        category: 'Antilipemic/Statin',
        manufacturer: 'Pfizer',
        otherNames: ['Lipitor', 'Atorva', 'Atocor']
    },
    {
        name: 'Simvastatin',
        uses: 'High cholesterol, high triglycerides, prevention of cardiovascular events in high-risk patients',
        dosage: '5-40mg once daily in the evening (max 40mg daily due to increased risk of myopathy at higher doses)',
        mechanism: 'HMG-CoA reductase inhibitor (statin) that reduces cholesterol production in the liver and increases LDL receptor expression',
        onset: '2 weeks (noticeable lipid changes)',
        duration: '12-24 hours',
        sideEffects: [
            'Muscle pain/weakness (myalgia)',
            'Headache',
            'Nausea/vomiting',
            'Constipation',
            'Abdominal pain',
            'Liver enzyme elevations',
            'Increased blood sugar/diabetes risk',
            'Memory problems/confusion (rare)',
            'Liver damage (rare)'
        ],
        precautions: [
            'Take in the evening (cholesterol synthesis is highest at night)',
            'AVOID grapefruit/grapefruit juice (significantly increases drug levels)',
            'Report unexplained muscle pain/tenderness/weakness immediately',
            'Limit alcohol intake',
            'May increase blood sugar (monitor if diabetic)',
            'Avoid in active liver disease or unexplained elevated liver enzymes',
            'Dose adjustment needed with certain medications (check for interactions)'
        ],
        howToTake: 'Take in the evening, with or without food. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'X',
        pregnancyNotes: 'Contraindicated in pregnancy (risk of fetal harm)',
        breastfeedingInfo: 'Contraindicated (may cause serious side effects in nursing infant)',
        category: 'Antilipemic/Statin',
        manufacturer: 'Merck & Co.',
        otherNames: ['Zocor', 'Simlup', 'Simvotin']
    },
    {
        name: 'Carvedilol',
        uses: 'Heart failure (mild to severe), hypertension (high blood pressure), left ventricular dysfunction after heart attack',
        dosage: '3.125-25mg twice daily (heart failure: start low and titrate up), 6.25-25mg twice daily (hypertension)',
        mechanism: 'Non-selective beta-adrenergic and alpha-1 adrenergic receptor blocker that reduces cardiac workload and oxygen demand while decreasing vascular resistance',
        onset: '1-2 hours',
        duration: '7-10 hours (twice daily dosing required)',
        sideEffects: [
            'Dizziness/lightheadedness',
            'Fatigue/weakness',
            'Low blood pressure',
            'Slow heart rate (bradycardia)',
            'Weight gain',
            'Diarrhea',
            'Hyperglycemia (increased blood sugar)',
            'Bronchospasm (in predisposed patients)',
            'Edema (swelling)'
        ],
        precautions: [
            'Take with food to reduce risk of low blood pressure',
            'Monitor blood pressure and heart rate regularly',
            'DO NOT stop suddenly (taper over 1-2 weeks)',
            'May mask symptoms of low blood sugar in diabetics',
            'Use with caution in patients with asthma/COPD',
            'May cause dizziness (use caution when driving)',
            'Report shortness of breath, swelling, or significant weight gain'
        ],
        howToTake: 'Take with food to minimize dizziness. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C (first trimester), D (second/third trimesters)',
        pregnancyNotes: 'Use only if potential benefit justifies potential risk to fetus',
        breastfeedingInfo: 'Not recommended (passes into breast milk)',
        category: 'Antihypertensive/Beta Blocker',
        manufacturer: 'GlaxoSmithKline',
        otherNames: ['Coreg', 'Coreg CR', 'Carloc']
    },
    {
        name: 'Diltiazem',
        uses: 'Hypertension (high blood pressure), chronic stable angina, vasospastic angina, certain heart rhythm disorders (atrial fibrillation/flutter, paroxysmal supraventricular tachycardia)',
        dosage: '120-360mg daily in divided doses (immediate-release), 180-360mg once daily (extended-release)',
        mechanism: 'Calcium channel blocker that inhibits calcium ion influx during cardiac and vascular smooth muscle contraction, resulting in coronary and peripheral vasodilation',
        onset: '30-60 minutes (oral)',
        duration: '4-8 hours (immediate-release), 12-24 hours (extended-release)',
        sideEffects: [
            'Swelling of ankles/feet (peripheral edema)',
            'Dizziness/lightheadedness',
            'Headache',
            'Flushing',
            'Nausea',
            'Constipation',
            'Low blood pressure',
            'Slow heart rate',
            'Fatigue',
            'Rash'
        ],
        precautions: [
            'Avoid grapefruit/grapefruit juice (increases drug levels)',
            'Rise slowly from sitting/lying position',
            'Monitor blood pressure and heart rate regularly',
            'Use with caution in liver/kidney disease',
            'Do not crush or chew extended-release formulations',
            'Avoid alcohol (may increase blood pressure-lowering effect)',
            'Report irregular heartbeat, severe dizziness, or swelling of hands/feet'
        ],
        howToTake: 'Take with or without food. Swallow extended-release tablets whole; do not crush or chew.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Use only if potential benefit justifies potential risk to fetus',
        breastfeedingInfo: 'Not recommended (passes into breast milk)',
        category: 'Antihypertensive/Calcium Channel Blocker',
        manufacturer: 'Various manufacturers',
        otherNames: ['Cardizem', 'Tiazac', 'Cartia XT', 'Dilacor XR']
    },
    {
        name: 'Furosemide',
        uses: 'Edema (fluid retention) due to heart failure, liver cirrhosis, kidney disease; hypertension (high blood pressure); pulmonary edema',
        dosage: '20-80mg daily or twice daily (edema), 40mg twice daily (hypertension), adjust based on response',
        mechanism: 'Loop diuretic that inhibits sodium and chloride reabsorption in the ascending loop of Henle, promoting water and electrolyte excretion',
        onset: '30-60 minutes (oral), 5 minutes (IV)',
        duration: '6-8 hours (oral), 2 hours (IV)',
        sideEffects: [
            'Dehydration',
            'Low potassium (hypokalemia)',
            'Low sodium (hyponatremia)',
            'Dizziness/lightheadedness',
            'Headache',
            'Increased blood sugar',
            'Increased uric acid (may trigger gout)',
            'Hearing loss (with high doses or rapid IV)',
            'Low blood pressure',
            'Muscle cramps'
        ],
        precautions: [
            'Take in morning to avoid nighttime urination',
            'Monitor weight daily (report sudden changes)',
            'Eat potassium-rich foods (bananas, oranges, potatoes)',
            'Rise slowly from sitting/lying position',
            'Monitor blood pressure regularly',
            'Report signs of electrolyte imbalance (muscle cramps, weakness, irregular heartbeat)',
            'Use sunscreen (increased sensitivity to sunlight)'
        ],
        howToTake: 'Take with or without food. Take the last dose by mid-afternoon to avoid nighttime urination.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Use only if potential benefit justifies potential risk to fetus',
        breastfeedingInfo: 'Not recommended (passes into breast milk, may suppress lactation)',
        category: 'Diuretic/Loop Diuretic',
        manufacturer: 'Various manufacturers',
        otherNames: ['Lasix', 'Frusol', 'Frusemide']
    },
    {
        name: 'Hydrochlorothiazide (HCTZ)',
        uses: 'Hypertension (high blood pressure), edema (fluid retention) due to heart failure, kidney disorders, or liver cirrhosis',
        dosage: '12.5-50mg once daily (max 50mg/day)',
        mechanism: 'Thiazide diuretic that inhibits sodium reabsorption in the distal convoluted tubule, promoting water and electrolyte excretion',
        onset: '2 hours',
        duration: '6-12 hours',
        sideEffects: [
            'Low potassium (hypokalemia)',
            'Increased urination',
            'Dizziness/lightheadedness',
            'Low sodium (hyponatremia)',
            'Increased blood sugar',
            'Increased uric acid (may trigger gout)',
            'Increased cholesterol/triglycerides',
            'Sensitivity to sunlight',
            'Impotence',
            'Muscle cramps/weakness'
        ],
        precautions: [
            'Take in morning to avoid nighttime urination',
            'Eat potassium-rich foods (bananas, oranges, spinach)',
            'Limit salt intake',
            'Monitor blood pressure regularly',
            'May increase blood sugar (monitor if diabetic)',
            'Use sunscreen (increased sun sensitivity)',
            'Avoid alcohol (may increase blood pressure-lowering effect)'
        ],
        howToTake: 'Take in the morning with or without food. Take with food if stomach upset occurs.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'B (first trimester), D (second/third trimesters)',
        pregnancyNotes: 'Not recommended for treatment of edema in pregnancy',
        breastfeedingInfo: 'Not recommended (passes into breast milk, may suppress lactation)',
        category: 'Diuretic/Thiazide',
        manufacturer: 'Various manufacturers',
        otherNames: ['Microzide', 'Oretic', 'Esidrix']
    },
    // Mental Health (51-70)
    {
        name: 'Sertraline',
        uses: 'Major depressive disorder (MDD), obsessive-compulsive disorder (OCD), panic disorder, post-traumatic stress disorder (PTSD), social anxiety disorder (SAD), premenstrual dysphoric disorder (PMDD)',
        dosage: '50-200mg once daily (start with 25-50mg and titrate up)',
        mechanism: 'Selective serotonin reuptake inhibitor (SSRI) that increases serotonin levels in the brain by blocking its reabsorption (reuptake) into neurons',
        onset: '1-4 weeks (initial response), 4-6 weeks (full effect)',
        duration: '24 hours (once daily dosing)',
        sideEffects: [
            'Nausea/vomiting',
            'Insomnia or drowsiness',
            'Sexual dysfunction (decreased libido, delayed orgasm)',
            'Diarrhea or constipation',
            'Dry mouth',
            'Dizziness',
            'Headache',
            'Increased sweating',
            'Fatigue',
            'Weight changes',
            'Tremor',
            'Agitation or restlessness'
        ],
        precautions: [
            'Increased risk of suicidal thoughts/behavior in children/young adults (monitor closely)',
            'Do not stop abruptly (taper gradually)',
            'May increase bleeding risk (especially with NSAIDs, aspirin, warfarin)',
            'Caution with other serotonergic drugs (risk of serotonin syndrome)',
            'May trigger manic episode in bipolar disorder',
            'Avoid alcohol (may increase CNS depression)',
            'Use caution when driving/operating machinery (may cause drowsiness/dizziness)'
        ],
        howToTake: 'Take with or without food, preferably in the morning. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Weigh risks vs benefits; may cause neonatal complications if used in third trimester',
        breastfeedingInfo: 'Passes into breast milk in small amounts; use with caution',
        category: 'Antidepressant/SSRI',
        manufacturer: 'Pfizer',
        otherNames: ['Zoloft', 'Lustral', 'Sertral']
    },
    {
        name: 'Escitalopram',
        uses: 'Major depressive disorder (MDD), generalized anxiety disorder (GAD), panic disorder, social anxiety disorder (SAD)',
        dosage: '10-20mg once daily (start with 10mg and titrate up)',
        mechanism: 'Selective serotonin reuptake inhibitor (SSRI) that enhances serotonin activity by blocking its reuptake into presynaptic neurons',
        onset: '1-4 weeks (initial response), 4-6 weeks (full effect)',
        duration: '24 hours (once daily dosing)',
        sideEffects: [
            'Nausea',
            'Insomnia or drowsiness',
            'Sexual dysfunction (decreased libido, delayed orgasm)',
            'Fatigue',
            'Dry mouth',
            'Dizziness',
            'Sweating',
            'Headache',
            'Diarrhea or constipation',
            'Appetite/weight changes'
        ],
        precautions: [
            'Increased risk of suicidal thoughts/behavior in children/young adults (monitor closely)',
            'Do not stop abruptly (taper gradually)',
            'May increase bleeding risk (especially with NSAIDs, aspirin, warfarin)',
            'Risk of serotonin syndrome with other serotonergic drugs',
            'May trigger manic episode in bipolar disorder',
            'Avoid alcohol (may increase CNS depression)',
            'Use caution when driving/operating machinery (may cause drowsiness/dizziness)'
        ],
        howToTake: 'Take in the morning or evening, with or without food. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Weigh risks vs benefits; may cause neonatal complications if used in third trimester',
        breastfeedingInfo: 'Passes into breast milk in small amounts; use with caution',
        category: 'Antidepressant/SSRI',
        manufacturer: 'Lundbeck',
        otherNames: ['Lexapro', 'Cipralex', 'Esipram']
    },
    {
        name: 'Fluoxetine',
        uses: 'Major depressive disorder (MDD), obsessive-compulsive disorder (OCD), bulimia nervosa, panic disorder, premenstrual dysphoric disorder (PMDD)',
        dosage: '20-80mg once daily (start with 20mg and titrate up)',
        mechanism: 'Selective serotonin reuptake inhibitor (SSRI) that increases serotonin levels in the brain by blocking its reabsorption (reuptake) into neurons',
        onset: '1-4 weeks (initial response), 4-6 weeks (full effect)',
        duration: '24-96 hours (long half-life of active metabolite)',
        sideEffects: [
            'Nausea/vomiting',
            'Insomnia or drowsiness',
            'Headache',
            'Nervousness/anxiety',
            'Decreased appetite/weight loss',
            'Sexual dysfunction',
            'Dry mouth',
            'Sweating',
            'Tremor',
            'Rash',
            'Fatigue/weakness',
            'Diarrhea or constipation'
        ],
        precautions: [
            'Increased risk of suicidal thoughts/behavior in children/young adults (monitor closely)',
            'Long half-life (takes weeks to clear from system)',
            'Many drug interactions (check with doctor/pharmacist)',
            'May increase bleeding risk (especially with NSAIDs, aspirin, warfarin)',
            'Risk of serotonin syndrome with other serotonergic drugs',
            'May trigger manic episode in bipolar disorder',
            'Avoid alcohol (may increase CNS depression)',
            'Use caution when driving/operating machinery (may cause drowsiness/dizziness)'
        ],
        howToTake: 'Take in the morning with or without food. Swallow whole with water.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Weigh risks vs benefits; may cause neonatal complications if used in third trimester',
        breastfeedingInfo: 'Passes into breast milk; use with caution',
        category: 'Antidepressant/SSRI',
        manufacturer: 'Eli Lilly',
        otherNames: ['Prozac', 'Sarafem', 'Selfemra']
    },
    {
        name: 'Venlafaxine',
        uses: 'Major depressive disorder (MDD), generalized anxiety disorder (GAD), social anxiety disorder (SAD), panic disorder',
        dosage: '37.5-225mg once daily (immediate-release), 37.5-225mg once daily (extended-release)',
        mechanism: 'Serotonin-norepinephrine reuptake inhibitor (SNRI) that increases levels of serotonin and norepinephrine in the brain',
        onset: '1-2 weeks (initial response), 4-6 weeks (full effect)',
        duration: '12 hours (immediate-release), 24 hours (extended-release)',
        sideEffects: [
            'Nausea/vomiting',
            'Headache',
            'Insomnia or drowsiness',
            'Dry mouth',
            'Dizziness',
            'Sweating',
            'Nervousness/anxiety',
            'Loss of appetite/weight loss',
            'Constipation',
            'Sexual dysfunction',
            'Increased blood pressure',
            'Withdrawal symptoms if stopped abruptly'
        ],
        precautions: [
            'DO NOT stop abruptly (must taper gradually over weeks to months)',
            'Monitor blood pressure regularly (may cause sustained increase)',
            'Increased risk of suicidal thoughts/behavior in children/young adults',
            'Risk of serotonin syndrome with other serotonergic drugs',
            'May increase bleeding risk (especially with NSAIDs, aspirin, warfarin)',
            'May trigger manic episode in bipolar disorder',
            'Avoid alcohol (may increase CNS depression)'
        ],
        howToTake: 'Take with food at about the same time each day. Swallow extended-release capsules whole; do not crush, chew, or dissolve.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule. Never double dose.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Weigh risks vs benefits; may cause neonatal complications if used in third trimester',
        breastfeedingInfo: 'Not recommended (passes into breast milk)',
        category: 'Antidepressant/SNRI',
        manufacturer: 'Pfizer',
        otherNames: ['Effexor', 'Effexor XR', 'Venlafexin']
    },
    {
        name: 'Bupropion',
        uses: 'Major depressive disorder (MDD), seasonal affective disorder (SAD), smoking cessation (Zyban), attention deficit hyperactivity disorder (ADHD) - off-label',
        dosage: '150-450mg daily in divided doses (immediate-release), 150-450mg once daily (sustained/XL release)',
        mechanism: 'Atypical antidepressant that inhibits the reuptake of norepinephrine and dopamine (NDRI), with minimal effect on serotonin',
        onset: '1-3 weeks (initial response), 4-6 weeks (full effect)',
        duration: '8-24 hours (varies by formulation)',
        sideEffects: [
            'Insomnia',
            'Dry mouth',
            'Headache',
            'Nausea/vomiting',
            'Constipation',
            'Dizziness',
            'Tremor',
            'Excessive sweating',
            'Weight loss',
            'Anxiety/agitation',
            'Increased heart rate',
            'Seizures (dose-related)'
        ],
        precautions: [
            'Increased risk of seizures (especially with higher doses, eating disorders, or history of seizures)',
            'Do not exceed 450mg daily',
            'May cause insomnia (take early in the day)',
            'May increase blood pressure (monitor regularly)',
            'Risk of angle-closure glaucoma',
            'Avoid alcohol (may lower seizure threshold)',
            'Do not take with MAOIs (14-day washout required)'
        ],
        howToTake: 'Take with or without food. Take immediate-release tablets 3-4 times daily, sustained-release twice daily, and extended-release once daily in the morning.',
        missedDose: 'Skip missed dose and take next dose at regular time. Never double dose.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Use only if potential benefit justifies potential risk to fetus',
        breastfeedingInfo: 'Passes into breast milk in small amounts; use with caution',
        category: 'Antidepressant/NDRI',
    },
    {
        name: 'Mirtazapine',
        uses: 'Major depressive disorder (MDD), generalized anxiety disorder (GAD), post-traumatic stress disorder (PTSD), insomnia, nausea/vomiting (off-label)',
        dosage: '15-45mg once daily at bedtime (start with 15mg and titrate up)',
        mechanism: 'Noradrenergic and specific serotonergic antidepressant (NaSSA) that enhances noradrenergic and serotonergic neurotransmission through antagonist activity at central presynaptic α2-adrenergic receptors and certain serotonin receptors',
        onset: '1-2 weeks (initial response), 4-6 weeks (full effect)',
        duration: '24 hours (once daily dosing)',
        sideEffects: [
            'Drowsiness/sedation (especially at lower doses)',
            'Increased appetite/weight gain',
            'Dry mouth',
            'Constipation',
            'Dizziness',
            'Increased cholesterol/triglycerides',
            'Abnormal dreams',
            'Peripheral edema',
            'Elevated liver enzymes'
        ],
        precautions: [
            'May cause significant sedation (use caution when driving/operating machinery)',
            'Monitor weight regularly',
            'May increase cholesterol/triglycerides (monitor lipid profile)',
            'May lower blood pressure (rise slowly from sitting/lying position)',
            'Avoid alcohol (may increase CNS depression)',
            'Use with caution in patients with liver/kidney disease',
            'May increase risk of suicidal thoughts/behavior in children/young adults'
        ],
        howToTake: 'Take at bedtime. May take with or without food, but take consistently.',
        missedDose: 'Skip missed dose and take next dose at regular time. Never double dose.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Use only if potential benefit justifies potential risk to fetus',
        breastfeedingInfo: 'Passes into breast milk; use with caution',
        category: 'Antidepressant/NaSSA',
        manufacturer: 'Merck & Co.',
        otherNames: ['Remeron', 'Remeron SolTab', 'Zispin', 'Mirtaz']
    },
    {
        name: 'Quetiapine',
        uses: 'Schizophrenia, bipolar disorder (manic/mixed/depressive episodes), major depressive disorder (adjunct), generalized anxiety disorder (off-label)',
        dosage: '25-800mg daily in 1-3 divided doses (varies by indication and formulation)',
        mechanism: 'Atypical antipsychotic that acts as an antagonist at multiple neurotransmitter receptors, including dopamine D2 and serotonin 5-HT2A receptors',
        onset: '1-2 weeks (initial effects), 4-6 weeks (full therapeutic effect)',
        duration: '6-12 hours (immediate-release), 24 hours (extended-release)',
        sideEffects: [
            'Drowsiness/sedation',
            'Dizziness',
            'Weight gain',
            'Dry mouth',
            'Increased appetite',
            'Constipation',
            'Blurred vision',
            'Low blood pressure (especially when standing)',
            'Increased cholesterol/triglycerides',
            'Increased blood sugar/diabetes risk',
            'Extrapyramidal symptoms (less common than with typical antipsychotics)',
            'Tardive dyskinesia (with long-term use)'
        ],
        precautions: [
            'Monitor blood glucose and lipids regularly (increased risk of diabetes/dyslipidemia)',
            'Monitor weight/BMI regularly',
            'Rise slowly from sitting/lying position (risk of orthostatic hypotension)',
            'Avoid alcohol (may increase CNS depression)',
            'Use with caution in elderly patients with dementia-related psychosis (increased mortality risk)',
            'May cause cognitive/motor impairment (use caution when driving/operating machinery)',
            'Risk of neuroleptic malignant syndrome (rare but serious)'
        ],
        howToTake: 'Take with or without food. Swallow extended-release tablets whole; do not crush, chew, or break.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule. Never double dose.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Use only if potential benefit justifies potential risk to fetus',
        breastfeedingInfo: 'Not recommended (passes into breast milk)',
        category: 'Antipsychotic/Atypical',
        manufacturer: 'AstraZeneca',
        otherNames: ['Seroquel', 'Seroquel XR', 'Ketipinor']
    },
    {
        name: 'Aripiprazole',
        uses: 'Schizophrenia, bipolar I disorder (acute manic/mixed episodes, maintenance, and adjunctive therapy), major depressive disorder (adjunct), irritability associated with autistic disorder, Tourette\'s disorder',
        dosage: '2-30mg once daily (varies by indication and age)',
        mechanism: 'Atypical antipsychotic that acts as a partial agonist at dopamine D2 and serotonin 5-HT1A receptors and as an antagonist at serotonin 5-HT2A receptor',
        onset: '1-2 weeks (initial response), 4-6 weeks (full therapeutic effect)',
        duration: 'Approximately 75 hours (half-life of active metabolite)',
        sideEffects: [
            'Akathisia (restlessness)',
            'Weight gain (less than with other atypical antipsychotics)',
            'Headache',
            'Insomnia',
            'Anxiety',
            'Nausea',
            'Vomiting',
            'Constipation',
            'Dizziness',
            'Extrapyramidal symptoms (less common than with typical antipsychotics)'
        ],
        precautions: [
            'Increased mortality in elderly patients with dementia-related psychosis',
            'Monitor for worsening depression or suicidal thoughts/behavior',
            'May impair judgment, thinking, or motor skills (caution when operating machinery)',
            'May cause orthostatic hypotension (rise slowly from sitting/lying position)',
            'May cause seizures (use caution in patients with seizure disorders)',
            'May increase risk of hyperglycemia/diabetes (monitor blood glucose)'
        ],
        howToTake: 'Take with or without food. Swallow tablets whole; do not split or chew.',
        missedDose: 'Take as soon as you remember. If near next dose, skip missed dose and resume schedule. Never double dose.',
        storage: 'Store at room temperature away from light and moisture',
        pregnancyCategory: 'C',
        pregnancyNotes: 'Use only if potential benefit justifies potential risk to fetus',
        breastfeedingInfo: 'Not recommended (passes into breast milk)',
        category: 'Antipsychotic/Atypical',
        manufacturer: 'Otsuka Pharmaceutical',
        otherNames: ['Abilify', 'Abilify Maintena', 'Abilify MyCite']
    },
    {
        name: 'Lorazepam',
        uses: 'Anxiety, insomnia, seizures',
        dosage: '0.5-6mg daily in divided doses',
        sideEffects: 'Drowsiness, dizziness, dependence',
        precautions: 'Short-term use only, risk of dependence',
        category: 'Benzodiazepine'
    },
    {
        name: 'Trazodone',
        uses: 'Depression, insomnia',
        dosage: '50-400mg at bedtime',
        sideEffects: 'Drowsiness, dizziness, dry mouth',
        precautions: 'Take with food, rise slowly',
        category: 'SARI'
    },
    // Diabetes (71-90)
    {
        name: 'Metformin',
        uses: 'Type 2 diabetes, PCOS',
        dosage: '500-2000mg daily in divided doses',
        sideEffects: 'Upset stomach, diarrhea, metallic taste',
        precautions: 'Take with food, monitor kidney function',
        category: 'Biguanide'
    },
    {
        name: 'Glipizide',
        uses: 'Type 2 diabetes',
        dosage: '2.5-40mg daily before meals',
        sideEffects: 'Low blood sugar, weight gain, dizziness',
        precautions: 'Take 30 minutes before meals',
        category: 'Sulfonylurea'
    },
    {
        name: 'Sitagliptin',
        uses: 'Type 2 diabetes',
        dosage: '25-100mg once daily',
        sideEffects: 'Upper respiratory infection, headache',
        precautions: 'May cause joint pain',
        category: 'DPP-4 Inhibitor'
    },
    {
        name: 'Empagliflozin',
        uses: 'Type 2 diabetes, heart failure',
        dosage: '10-25mg once daily',
        sideEffects: 'Urinary tract infections, dehydration',
        precautions: 'Drink plenty of fluids',
        category: 'SGLT2 Inhibitor'
    },
    {
        name: 'Liraglutide',
        uses: 'Type 2 diabetes, weight management',
        dosage: '0.6-3mg daily injection',
        sideEffects: 'Nausea, diarrhea, headache',
        precautions: 'Injection site reactions',
        category: 'GLP-1 Agonist'
    },
    {
        name: 'Pioglitazone',
        uses: 'Type 2 diabetes',
        dosage: '15-45mg once daily',
        sideEffects: 'Weight gain, fluid retention, fractures',
        precautions: 'May increase risk of heart failure',
        category: 'Thiazolidinedione'
    },
    {
        name: 'Insulin Glargine',
        uses: 'Type 1 and 2 diabetes',
        dosage: 'Individualized, once daily injection',
        sideEffects: 'Low blood sugar, weight gain',
        precautions: 'Rotate injection sites',
        category: 'Long-Acting Insulin'
    },
    {
        name: 'Insulin Aspart',
        uses: 'Type 1 and 2 diabetes',
        dosage: 'Individualized, with meals',
        sideEffects: 'Low blood sugar, injection site reactions',
        precautions: 'Meal-related dosing',
        category: 'Rapid-Acting Insulin'
    },
    {
        name: 'Canagliflozin',
        uses: 'Type 2 diabetes, heart disease',
        dosage: '100-300mg once daily',
        sideEffects: 'Urinary tract infections, increased urination',
        precautions: 'Monitor for yeast infections',
        category: 'SGLT2 Inhibitor'
    },
    {
        name: 'Semaglutide',
        uses: 'Type 2 diabetes, obesity',
        dosage: '0.5-1mg weekly injection',
        sideEffects: 'Nausea, diarrhea, abdominal pain',
        precautions: 'May delay stomach emptying',
        category: 'GLP-1 Agonist'
    },
    // Allergy & Respiratory (91-110)
    {
        name: 'Loratadine',
        uses: 'Allergies, hives',
        dosage: '10mg once daily',
        sideEffects: 'Headache, dry mouth, fatigue',
        precautions: 'Non-drowsy formula',
        category: 'Antihistamine'
    },
    {
        name: 'Cetirizine',
        uses: 'Allergies, chronic hives',
        dosage: '5-10mg once daily',
        sideEffects: 'Drowsiness, dry mouth, fatigue',
        precautions: 'May cause drowsiness in some people',
        category: 'Antihistamine'
    },
    {
        name: 'Fexofenadine',
        uses: 'Seasonal allergies, hives',
        dosage: '60-180mg once daily',
        sideEffects: 'Headache, dizziness, nausea',
        precautions: 'Take with water, avoid fruit juices',
        category: 'Antihistamine'
    },
    {
        name: 'Montelukast',
        uses: 'Asthma, allergies',
        dosage: '10mg once daily in evening',
        sideEffects: 'Headache, dizziness, rash',
        precautions: 'Monitor for mood changes',
        category: 'Leukotriene Inhibitor'
    },
    {
        name: 'Fluticasone Nasal',
        uses: 'Nasal allergies, congestion',
        dosage: '1-2 sprays per nostril daily',
        sideEffects: 'Nasal irritation, headache',
        precautions: 'Prime before first use',
        category: 'Nasal Steroid'
    },
    {
        name: 'Albuterol',
        uses: 'Asthma, bronchospasm',
        dosage: '1-2 puffs every 4-6 hours as needed',
        sideEffects: 'Nervousness, shakiness, fast heartbeat',
        precautions: 'Rinse mouth after use',
        category: 'Bronchodilator'
    },
    {
        name: 'Fluticasone/Salmeterol',
        uses: 'Asthma, COPD',
        dosage: '1 inhalation twice daily',
        sideEffects: 'Thrush, hoarseness, headache',
        precautions: 'Rinse mouth after use',
        category: 'Inhaled Corticosteroid/LABA'
    },
    {
        name: 'Ipratropium',
        uses: 'COPD, bronchospasm',
        dosage: '2 puffs every 4-6 hours',
        sideEffects: 'Dry mouth, cough, blurred vision',
        precautions: 'Avoid eyes',
        category: 'Anticholinergic'
    },
    {
        name: 'Phenylephrine',
        uses: 'Nasal congestion',
        dosage: '10mg every 4 hours as needed',
        sideEffects: 'Nervousness, dizziness, sleeplessness',
        precautions: 'Do not use more than 3 days',
        category: 'Decongestant'
    },
    {
        name: 'Dextromethorphan/Guaifenesin',
        uses: 'Cough, chest congestion',
        dosage: '10-20mL every 4 hours',
        sideEffects: 'Dizziness, nausea, drowsiness',
        precautions: 'Drink plenty of fluids',
        category: 'Cough/Cold'
    },
    {
        name: 'Amoxicillin',
        uses: 'Bacterial infections',
        dosage: '250-500mg every 8 hours',
        sideEffects: 'Diarrhea, nausea, rash',
        precautions: 'Complete full course, may reduce effectiveness of birth control',
        category: 'Antibiotic'
    },
    {
        name: 'Lisinopril',
        uses: 'High blood pressure, heart failure',
        dosage: '10-40mg once daily',
        sideEffects: 'Dry cough, dizziness, high potassium levels',
        precautions: 'Monitor kidney function, avoid potassium supplements',
        category: 'ACE Inhibitor'
    },
    {
        name: 'Atorvastatin',
        uses: 'High cholesterol',
        dosage: '10-80mg once daily',
        sideEffects: 'Muscle pain, digestive problems, liver enzyme abnormalities',
        precautions: 'Avoid grapefruit, monitor liver enzymes',
        category: 'Statin'
    },
    {
        name: 'Metformin',
        uses: 'Type 2 diabetes',
        dosage: '500-2000mg daily in divided doses',
        sideEffects: 'Nausea, diarrhea, stomach upset',
        precautions: 'Take with meals, monitor kidney function',
        category: 'Biguanide'
    },
    {
        name: 'Omeprazole',
        uses: 'Acid reflux, stomach ulcers',
        dosage: '20-40mg once daily',
        sideEffects: 'Headache, diarrhea, stomach pain',
        precautions: 'Take before meals, long-term use may affect bone health',
        category: 'Proton Pump Inhibitor'
    },
    {
        name: 'Sertraline',
        uses: 'Depression, anxiety disorders',
        dosage: '50-200mg once daily',
        sideEffects: 'Nausea, insomnia, sexual dysfunction',
        precautions: 'Do not stop suddenly, may take 4-6 weeks for full effect',
        category: 'SSRI'
    },
    {
        name: 'Albuterol',
        uses: 'Asthma, COPD',
        dosage: '1-2 puffs every 4-6 hours as needed',
        sideEffects: 'Nervousness, shakiness, rapid heartbeat',
        precautions: 'Do not exceed recommended dose, rinse mouth after use',
        category: 'Bronchodilator'
    },
    {
        name: 'Levothyroxine',
        uses: 'Hypothyroidism',
        dosage: 'Dose varies by patient (25-200mcg daily)',
        sideEffects: 'Hair loss, weight changes, irregular heartbeat',
        precautions: 'Take on empty stomach, avoid calcium/iron supplements within 4 hours',
        category: 'Thyroid Hormone'
    }
];

// Function to find medicine by name
function findMedicineByName(name) {
    return window.medicines.find(med => 
        med.name.toLowerCase() === name.toLowerCase()
    );
}

// Function to search medicines
function searchMedicines(query) {
    if (!query) return [];
    const searchTerm = query.toLowerCase();
    return window.medicines.filter(med => 
        med.name.toLowerCase().includes(searchTerm) ||
        (med.category && med.category.toLowerCase().includes(searchTerm)) ||
        (med.uses && med.uses.toLowerCase().includes(searchTerm))
    );
}

// Function to display medicines
function displayMedicines() {
    const container = document.getElementById('medicines-container');
    if (!container) return;

    medicines.forEach(med => {
        const medCard = document.createElement('div');
        medCard.className = 'medicine-card';
        medCard.innerHTML = `
            <h3>${med.name} <span class="category">(${med.category})</span></h3>
            <p><strong>Uses:</strong> ${med.uses}</p>
            <p><strong>Dosage:</strong> ${med.dosage}</p>
            <p><strong>Side Effects:</strong> ${med.sideEffects}</p>
            <p><strong>Precautions:</strong> ${med.precautions}</p>
        `;
        container.appendChild(medCard);
    });
}

// Call the function when the page loads
document.addEventListener('DOMContentLoaded', displayMedicines);
